# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLineEdit {\n"
"    background-color:rgb(74, 162, 36);\n"
"    border:none;\n"
"    border-radius:7px;\n"
"    color:white;    \n"
"    font-size:15px;\n"
"}\n"
"\n"
"QLineEdit:hover,\n"
"QLineEdit:focus  {\n"
"    background-color:rgb(30, 91, 0);\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    color:white;\n"
"}\n"
"\n"
"QFrame#container {\n"
"    background-color: rgb(34, 34, 34);\n"
"    border:1px solid rgb(74, 162, 36);\n"
"\n"
"}\n"
"\n"
"QLabel#appName {\n"
"    background-color: rgb(74, 162, 36);\n"
"\n"
"}\n"
"\n"
"QLineEdit#columnsInA_input, QLineEdit#columnsInB_input, QLineEdit#rowsInA_input , QLineEdit#rowsInB_input   {\n"
"    background-color:transparent;\n"
"    border:none;\n"
"    border-bottom:2px solid rgb(30, 91, 0);\n"
"    color:white;\n"
"    border-radius:none\n"
"}\n"
"\n"
"QLineEdit#columnsInA_input:hover, QLineEdit#columnsInB_input:hover, QLineEdit#rowsInA_input:hover , QLineEdit#rowsInB_input:hover  {\n"
"    background-color:transparent;\n"
"    border:none;\n"
"    border-bottom:2px solid  rgb(74, 162, 36);\n"
"}\n"
"\n"
"QLineEdit#columnsInA_input:focus, QLineEdit#columnsInB_input:focus, QLineEdit#rowsInA_input:focus, QLineEdit#rowsInB_input:focus {\n"
"    background-color:transparent;\n"
"    border:none;\n"
"    border-bottom:2px solid  rgb(74, 162, 36);\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(66, 66, 66);\n"
"    color:white;\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(74, 162, 36)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(39, 118, 0)\n"
"}\n"
"\n"
"QLabel#result {\n"
"    border:2px solid rgb(74, 162, 36);\n"
"    border-top:none;\n"
"    border-bottom:none;\n"
"    border-radius:20px\n"
"}\n"
"\n"
"QPushButton#closeBtn {\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"QPushButton#closeBtn:hover {\n"
"    background-color:red;\n"
"}\n"
"\n"
"QLabel#multiplierError {\n"
"    background-color:rgb(255, 28, 58) ;\n"
"    border-bottom-right-radius:15px;\n"
"    border-bottom-left-radius:15px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.container = QtWidgets.QFrame(self.centralwidget)
        self.container.setGeometry(QtCore.QRect(20, 10, 801, 900))
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.rowsInB = QtWidgets.QLabel(self.container)
        self.rowsInB.setGeometry(QtCore.QRect(116, 34, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rowsInB.setFont(font)
        self.rowsInB.setObjectName("rowsInB")
        self.multiplier = QtWidgets.QPushButton(self.container)
        self.multiplier.setGeometry(QtCore.QRect(670, 850, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.multiplier.setFont(font)
        self.multiplier.setObjectName("multiplier")
        self.nameFirstMartrix = QtWidgets.QLabel(self.container)
        self.nameFirstMartrix.setGeometry(QtCore.QRect(10, 100, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nameFirstMartrix.setFont(font)
        self.nameFirstMartrix.setAlignment(QtCore.Qt.AlignCenter)
        self.nameFirstMartrix.setObjectName("nameFirstMartrix")
        self.columnsInB = QtWidgets.QLabel(self.container)
        self.columnsInB.setGeometry(QtCore.QRect(127, 64, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.columnsInB.setFont(font)
        self.columnsInB.setTextFormat(QtCore.Qt.PlainText)
        self.columnsInB.setObjectName("columnsInB")
        self.columnsInB_input = QtWidgets.QLineEdit(self.container)
        self.columnsInB_input.setGeometry(QtCore.QRect(180, 60, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.columnsInB_input.setFont(font)
        self.columnsInB_input.setText("")
        self.columnsInB_input.setAlignment(QtCore.Qt.AlignCenter)
        self.columnsInB_input.setObjectName("columnsInB_input")
        self.rowsInA = QtWidgets.QLabel(self.container)
        self.rowsInA.setGeometry(QtCore.QRect(5, 34, 62, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rowsInA.setFont(font)
        self.rowsInA.setObjectName("rowsInA")
        self.columnsInA_input = QtWidgets.QLineEdit(self.container)
        self.columnsInA_input.setGeometry(QtCore.QRect(70, 60, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.columnsInA_input.setFont(font)
        self.columnsInA_input.setText("")
        self.columnsInA_input.setAlignment(QtCore.Qt.AlignCenter)
        self.columnsInA_input.setObjectName("columnsInA_input")
        self.rowsInA_input = QtWidgets.QLineEdit(self.container)
        self.rowsInA_input.setGeometry(QtCore.QRect(70, 30, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rowsInA_input.setFont(font)
        self.rowsInA_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rowsInA_input.setObjectName("rowsInA_input")
        self.rowsInB_input = QtWidgets.QLineEdit(self.container)
        self.rowsInB_input.setGeometry(QtCore.QRect(180, 30, 30, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rowsInB_input.setFont(font)
        self.rowsInB_input.setAlignment(QtCore.Qt.AlignCenter)
        self.rowsInB_input.setObjectName("rowsInB_input")
        self.columnsInA = QtWidgets.QLabel(self.container)
        self.columnsInA.setGeometry(QtCore.QRect(14, 64, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.columnsInA.setFont(font)
        self.columnsInA.setObjectName("columnsInA")
        self.appName = QtWidgets.QLabel(self.container)
        self.appName.setGeometry(QtCore.QRect(0, 0, 800, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setItalic(False)
        self.appName.setFont(font)
        self.appName.setTextFormat(QtCore.Qt.AutoText)
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.nameSecondMartrix = QtWidgets.QLabel(self.container)
        self.nameSecondMartrix.setGeometry(QtCore.QRect(480, 100, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.nameSecondMartrix.setFont(font)
        self.nameSecondMartrix.setAlignment(QtCore.Qt.AlignCenter)
        self.nameSecondMartrix.setObjectName("nameSecondMartrix")
        self.sum = QtWidgets.QPushButton(self.container)
        self.sum.setGeometry(QtCore.QRect(730, 850, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.sum.setFont(font)
        self.sum.setObjectName("sum")
        self.result = QtWidgets.QLabel(self.container)
        self.result.setGeometry(QtCore.QRect(20, 590, 261, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setIndent(-1)
        self.result.setObjectName("result")
        self.closeBtn = QtWidgets.QPushButton(self.container)
        self.closeBtn.setGeometry(QtCore.QRect(775, 0, 25, 25))
        self.closeBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\andre\\Desktop\\DesktopFolder\\Новая папка\\GUI\\matrix\\png-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon)
        self.closeBtn.setIconSize(QtCore.QSize(22, 22))
        self.closeBtn.setObjectName("closeBtn")
        self.multiplierError = QtWidgets.QLabel(self.container)
        self.multiplierError.setGeometry(QtCore.QRect(250, -16, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.multiplierError.setFont(font)
        self.multiplierError.setAlignment(QtCore.Qt.AlignCenter)
        self.multiplierError.setObjectName("multiplierError")
        self.multiplierError.raise_()
        self.rowsInB.raise_()
        self.multiplier.raise_()
        self.nameFirstMartrix.raise_()
        self.columnsInB.raise_()
        self.columnsInB_input.raise_()
        self.rowsInA.raise_()
        self.columnsInA_input.raise_()
        self.rowsInA_input.raise_()
        self.rowsInB_input.raise_()
        self.columnsInA.raise_()
        self.appName.raise_()
        self.nameSecondMartrix.raise_()
        self.sum.raise_()
        self.result.raise_()
        self.closeBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rowsInB.setText(_translate("MainWindow", "Columns B"))
        self.multiplier.setText(_translate("MainWindow", "A X B"))
        self.nameFirstMartrix.setText(_translate("MainWindow", "MATRIX <strong>A</strong>:"))
        self.columnsInB.setText(_translate("MainWindow", "Rows B"))
        self.rowsInA.setText(_translate("MainWindow", "Columns A"))
        self.columnsInA.setText(_translate("MainWindow", "Rows A"))
        self.appName.setText(_translate("MainWindow", "<strong>MATRIX</strong> CALCULATOR"))
        self.nameSecondMartrix.setText(_translate("MainWindow", "MATRIX <strong>B</strong>:"))
        self.sum.setText(_translate("MainWindow", "A + B"))
        self.result.setText(_translate("MainWindow", "TextLabel"))
        self.multiplierError.setText(_translate("MainWindow", "Неверная размерность матрицы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
